# Generated by Django 5.2.1 on 2025-06-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoProyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_proyectado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacion.escenariosimulacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='VariableEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_modificado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='simulacion.escenariosimulacion')),
            ],
        ),
    ]
