# Generated by Django 5.2.1 on 2025-06-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('clase', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital Contable'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='finanzas.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.periodo')),
            ],
            options={
                'unique_together': {('cuenta', 'periodo')},
            },
        ),
    ]
