# Generated by Django 5.2.1 on 2025-05-13 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_financiero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancegeneral',
            options={'verbose_name_plural': 'Balances Generales'},
        ),
        migrations.AlterModelOptions(
            name='estadoresultados',
            options={'verbose_name_plural': 'Estados de Resultados'},
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='activo_corriente',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='activo_no_corriente',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='id',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='pasivo_corriente',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='pasivo_no_corriente',
        ),
        migrations.RemoveField(
            model_name='balancegeneral',
            name='patrimonio',
        ),
        migrations.RemoveField(
            model_name='estadoresultados',
            name='gastos_no_operacionales',
        ),
        migrations.RemoveField(
            model_name='estadoresultados',
            name='gastos_operacionales',
        ),
        migrations.RemoveField(
            model_name='estadoresultados',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estadoresultados',
            name='impuestos',
        ),
        migrations.RemoveField(
            model_name='estadoresultados',
            name='ingresos',
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='activos_intangibles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='anticipo_proveedores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='aportacion_patrimonial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='bancos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='caja_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='capital_social',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='capital_variable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='clientes_nacionales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='cobros_anticipados_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='cuentas_por_pagar_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='cuentas_por_pagar_largo_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='deudores_diversos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='documentos_por_cobrar_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='documentos_por_cobrar_largo_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='documentos_por_pagar_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='documentos_por_pagar_largo_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='edificios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='equipo_computo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='equipo_comunicacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='estimacion_cuentas_incobrables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='gastos_instalacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='gastos_organizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='inventario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='inversiones_temporales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='iva_trasladado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='maquinaria_equipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='mobiliario_equipo_oficina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='otros_activos_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='otros_activos_fijos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='otros_pasivos_corto_plazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='pagos_anticipados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='perdida_ejercicios_anteriores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='reserva_legal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='terrenos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='utilidad_ejercicios_anteriores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='vehiculos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='fluctuacion_cambiaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='gastos_financieros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='gastos_operacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='impuesto_utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='perdida_ejercicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='productos_financieros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='utilidad_ejercicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='estadoresultados',
            name='ventas_netas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema_financiero.periodocontable'),
        ),
        migrations.AlterField(
            model_name='estadoresultados',
            name='costo_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estadoresultados',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema_financiero.periodocontable'),
        ),
    ]
