# Generated by Django 5.2.1 on 2025-05-14 00:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_financiero', '0002_alter_balancegeneral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancegeneral',
            name='utilidad_ejercicio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
